// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_posts_default = defineTool({
  name: "search_posts",
  title: "Search posts",
  description: "Search public posts on SocialHub by keyword. Returns id, content, category, and engagement counts.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to search post content for."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      globalThis.process.env.SUPABASE_URL,
      globalThis.process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("posts").select("id, content, category, likes_count, comments_count, shares_count, created_at").ilike("content", `%${query}%`).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trending-posts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_trending_posts_default = defineTool2({
  name: "get_trending_posts",
  title: "Get trending posts",
  description: "Fetch currently trending posts on SocialHub, optionally filtered by category.",
  inputSchema: {
    category: z2.string().trim().min(1).optional().describe("Optional category filter."),
    limit: z2.number().int().min(1).max(50).default(10).describe("Max results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient2(
      globalThis.process.env.SUPABASE_URL,
      globalThis.process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("posts").select("id, content, category, likes_count, comments_count, shares_count, engagement_rate, created_at").order("engagement_rate", { ascending: false, nullsFirst: false }).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "socialhub-mcp",
  title: "SocialHub MCP",
  version: "0.1.0",
  instructions: "Tools for SocialHub: search public posts and fetch trending posts. Read-only.",
  tools: [search_posts_default, get_trending_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
